-- ============================================================
-- COMPANIES
-- ============================================================

INSERT INTO companies (name, vat_number, company_type, industry, headquarters, website_url, digital_status, archived_at, founded_year, notes) VALUES
  ('Vortex Systems AB',     'SE556012345601',  'corporation',    'tech',        'Stockholm, Sweden',      'https://vortexsystems.se',    'active',   '2025-01-10T09:00:00Z', 2011, 'Enterprise SaaS. Active LinkedIn and Twitter presence.'),
  ('Graymount Consulting',  'GB123456789',     'agency',         'consulting',  'London, United Kingdom', 'https://graymount.co.uk',     'active',   '2024-11-20T14:00:00Z', 2016, 'Strategy consultancy. Regular LinkedIn updates.'),
  ('NordBridge NGO',        NULL,              'ngo',            'healthcare',  'Oslo, Norway',           'https://nordbridge.no',       'absent',   '2024-06-05T11:00:00Z', 2009, 'Dormant since mid-2023. Website still online.'),
  ('Kova Digital',          'DE298765432',     'startup',        'tech',        'Berlin, Germany',        'https://kova.io',             'bankrupt', '2023-09-01T00:00:00Z', 2020, 'Series A failed. Dissolved Q3 2023.'),
  ('Prism Retail GmbH',     'DE112233445',     'small_business', 'retail',      'Munich, Germany',        'https://prismretail.de',      'active',   '2025-03-01T08:00:00Z', 2018, 'Mid-size retail chain. Active social presence.'),
  ('Solara Finance',        'FR75123456789',   'corporation',    'finance',     'Paris, France',          'https://solarafinance.fr',    'absent',   '2024-08-14T10:00:00Z', 2014, 'Platform accounts frozen during regulatory review.'),
  ('Cloudnine Media',       NULL,              'agency',         'media',       'Los Angeles, USA',       'https://cloudninemedia.com',  'active',   '2025-02-18T12:00:00Z', 2019, 'Content production agency. Heavy YouTube presence.'),
  ('Relic Labs',            'US-EIN-83-4421',  'startup',        'tech',        'Austin, USA',            'https://reliclabs.io',        'bankrupt', '2022-11-30T00:00:00Z', 2021, 'Shut down after product pivot failed. Accounts archived.'),
  ('Meridian Health Group', 'ES12345678A',     'corporation',    'healthcare',  'Madrid, Spain',          'https://meridianhealth.es',   'active',   '2024-12-01T09:30:00Z', 2007, 'Hospital network. Active LinkedIn and Facebook.'),
  ('Hatch Collective',      NULL,              'ngo',            'consulting',  'Amsterdam, Netherlands', 'https://hatchcollective.nl',  'absent',   '2024-04-22T07:00:00Z', 2015, 'Social enterprise. Went dark after funding lapsed.'),
  ('ByteForge Studios',     'PL5260001234',    'startup',        'tech',        'Warsaw, Poland',         'https://byteforge.pl',        'active',   '2025-01-30T16:00:00Z', 2022, 'Indie game dev studio. Active Twitter and YouTube.'),
  ('Everline Logistics',    'NL123456789B01',  'corporation',    'retail',      'Rotterdam, Netherlands', 'https://everline.nl',         'active',   '2024-10-05T13:00:00Z', 2001, 'EU freight company. LinkedIn focused.');

INSERT INTO company_platform_profiles (company_id, platform_id, username, display_name, bio, follower_count, following_count, post_count, profile_url, is_active, last_seen_at) VALUES
  (1,  (SELECT id FROM platforms WHERE name='linkedin'),  'vortex-systems-ab',    'Vortex Systems AB',     'Enterprise SaaS solutions.',             18400, 320, 412, 'https://linkedin.com/company/vortex-systems-ab', TRUE,  '2026-02-01T10:00:00Z'),
  (1,  (SELECT id FROM platforms WHERE name='twitter'),   '@VortexSystemsAB',     'Vortex Systems',        'Building the future of enterprise.',      4200,  180, 890, 'https://twitter.com/VortexSystemsAB',           TRUE,  '2026-01-28T09:00:00Z'),
  (2,  (SELECT id FROM platforms WHERE name='linkedin'),  'graymount-consulting',  'Graymount Consulting',  'Strategy that scales.',                   9100,  210, 320, 'https://linkedin.com/company/graymount',         TRUE,  '2026-01-15T11:00:00Z'),
  (3,  (SELECT id FROM platforms WHERE name='linkedin'),  'nordbridge-ngo',        'NordBridge',            'Building health bridges across borders.',  3200,   80,  74, 'https://linkedin.com/company/nordbridge',        FALSE, '2023-05-10T08:00:00Z'),
  (4,  (SELECT id FROM platforms WHERE name='linkedin'),  'kova-digital',          'Kova Digital',          'We built things. While it lasted.',        1100,   60,  43, 'https://linkedin.com/company/kova-digital',      FALSE, '2023-08-20T12:00:00Z'),
  (5,  (SELECT id FROM platforms WHERE name='linkedin'),  'prism-retail-gmbh',     'Prism Retail GmbH',     'Retail reimagined.',                       6700,  140, 210, 'https://linkedin.com/company/prism-retail',      TRUE,  '2026-02-10T14:00:00Z'),
  (5,  (SELECT id FROM platforms WHERE name='instagram'), 'prismretail.de',        'Prism Retail',          'Your local favourite.',                    2100,  310, 180, 'https://instagram.com/prismretail.de',           TRUE,  '2026-02-08T16:00:00Z'),
  (6,  (SELECT id FROM platforms WHERE name='linkedin'),  'solara-finance',        'Solara Finance',        'Smart money for smart people.',           11200,  240, 280, 'https://linkedin.com/company/solara-finance',    FALSE, '2024-07-01T09:00:00Z'),
  (7,  (SELECT id FROM platforms WHERE name='youtube'),   'CloudnineMediaLA',      'Cloudnine Media',       'Stories worth telling.',                  88000,  410, 1230,'https://youtube.com/c/CloudnineMediaLA',         TRUE,  '2026-03-01T18:00:00Z'),
  (7,  (SELECT id FROM platforms WHERE name='instagram'), 'cloudninemedia',        'Cloudnine Media',       'Content. Always.',                        14000,  500, 430, 'https://instagram.com/cloudninemedia',           TRUE,  '2026-03-05T12:00:00Z'),
  (9,  (SELECT id FROM platforms WHERE name='linkedin'),  'meridian-health-group', 'Meridian Health Group', 'Caring across borders.',                   7800,  180, 310, 'https://linkedin.com/company/meridian-health',   TRUE,  '2026-01-20T10:00:00Z'),
  (9,  (SELECT id FROM platforms WHERE name='facebook'),  'MeridianHealthES',      'Meridian Health',       'Leading healthcare across Spain.',          4200,  120, 210, 'https://facebook.com/MeridianHealthES',          TRUE,  '2026-01-18T14:00:00Z'),
  (11, (SELECT id FROM platforms WHERE name='youtube'),   'ByteForgeStudios',      'ByteForge Studios',     'Play, build, repeat.',                    22000,  290, 540, 'https://youtube.com/c/ByteForgeStudios',         TRUE,  '2026-03-10T15:00:00Z'),
  (11, (SELECT id FROM platforms WHERE name='twitter'),   '@ByteForgeStudios',     'ByteForge Studios',     'Indie games from Warsaw.',                 5600,  120, 760, 'https://twitter.com/ByteForgeStudios',           TRUE,  '2026-03-12T11:00:00Z'),
  (12, (SELECT id FROM platforms WHERE name='linkedin'),  'everline-logistics',    'Everline Logistics',    'Moving Europe forward.',                   4300,   90, 175, 'https://linkedin.com/company/everline',          TRUE,  '2026-02-20T09:00:00Z');
